name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Versão estável do Node

      - name: Instalar dependências e testar o Servidor
        run: |
          cd Server
          npm install
          # npm test (Descomente esta linha quando criarmos os testes reais!)

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências e buildar o React
        run: |
          cd Client
          npm install
          npm run build # Garante que o React compila sem erros de sintaxe